sasjs/cli

- src/cli.js
- src/main.js
- src/sasjs-create/index.js
- src/sasjs-help/index.js
- src/utils/utils.js
* Create web app when `sasjs create` is used with the `-t` or `--template` option.
* Supported options:
* react
* angular
* minimal
> feat(create-web-apps): Add the ability to create web apps via the CLI

- src/sasjs-add/index.js
- src/utils/config-utils.js
> fix: Added number input to context selector

- src/utils/config-utils.js
> Disabled useMacroCore check for cb step

- src/sasjs-add/index.js
> fix: Added appLoc input on add local config

- src/sasjs-add/index.js
- src/sasjs-deploy/index.js
- src/utils/auth-utils.js
> fix: issue 37

- src/sasjs-deploy/index.js
> feat: added deployment scripts execution after deploy service pack step

- src/sasjs-web/sasjsout.js
> updates for JSON support

- src/sasjs-deploy/index.js
> fix: added check for not authenticated deployment to Viya

- .github/workflows/run-tests.yml
- test.sh
Fixes https://github.com/sasjs/cli/issues/100
Run a set of CLI commands to test the functionality as part of branch and PR builds.
* Added shell script that runs tests.
* Invoke script as part of test action.
> chore(ci): run CLI tests on each push

- package-lock.json
- package.json
- src/sasjs-request/index.js
No related issues.
Updated the minor version of adapter.
Fixed the call of `cwd()`
---
> fix: cwd() call, adapter bump

- package-lock.json
- package.json
- src/sasjs-request/index.js
No related issues.
Adapter version update.
package.json
> Adapter bump

- package-lock.json
- package.json
- src/sasjs-context/create.js
- src/sasjs-context/edit.js
- src/sasjs-context/export.js
- src/sasjs-context/index.js
- src/sasjs-context/list.js
- src/sasjs-context/remove.js
- src/sasjs-help/index.js
- src/sasjs-request/index.js
- src/utils/config-utils.js
- test/config-utils.spec.js
closes #105 
Added the ability to export context to JSON file.
> feat(context): added 'export' command

- src/sasjs-context/edit.js
- src/sasjs-context/index.js
Provide context name to the cli in order to change context name.
Update logic related to the context edit command.
> feat(context-edit): added context name to 'edit' command to update context name

- src/sasjs-help/index.js
No issue raised
Updating help text in sasjs help
src/sasjs-help/index.js
- [ x] Code is formatted correctly (`npm run lint:fix`).
- [ x] Any new functionality has been unit tested. no new functionality
- [x ] All unit tests are passing (`npm test`).
> docs: help updates for sasjs context

- src/main.js
closes #122 
Fix error message for `add` command.
> fix(error-message): fixed error message for 'add' command

- README.md
closes #113 
Provide instruction for updating the existing @sasjs/cli version.
This issue will be resolved in npm 7.
> chore(version-update): added note to readme

- src/sasjs-add/index.js
- src/utils/config-utils.js
closes #114 
Provide the location of the file in which the target was added.
Changed `saveToLocalConfig` and `saveGlobalRcFile`.
> chore(config): added print out messages to 'saveToLocalConfig' and 'saveGlobalRcFile' functions

- src/main.js
- src/sasjs-run/index.js
- src/utils/config-utils.js
- test/sasjs-run.spec.js
closes #75 
To fix running not *.sas files.
> fix(run): fixed running not *.sas files

- src/sasjs-run/index.js
- test/sasjs-run.spec.js
To fix regular expression in 'runSasCode' command.
> fix(run): fixed regular expression in 'runSasCode' command

- src/cli.js
- src/main.js
- src/sasjs-help/index.js
- src/sasjs-servicepack/deploy.js
- src/sasjs-servicepack/index.js
- src/utils/command-utils.js
- test/command-utils.spec.js
Closes #132 
Introducing `servicepack` command set. For now we have only `deploy` action.
> feat: servicepack deploy command

- .github/workflows/run-tests.yml
- .gitignore
- jest.config.js
- package-lock.json
- package.json
- src/sasjs-servicepack/deploy.js
- src/utils/config-utils.js
- src/utils/input-utils.js
- test/commands/servicepack/sasjs-servicepack.deploy.spec.js
- test/commands/servicepack/testServicepack.json
- test/config-utils.spec.js
#140
Unit test `sasjs servicepack deploy` command.
1. Fixed `sasjs-servicepack/deploy`.
2. Refactored `access_token` env.
3. Updated tests related dependencies.
4. Added unit test covering `sasjs servicepack deploy` command.
> test(servicepack-deploy): added unit tests

- src/sasjs-request/index.js
https://github.com/sasjs/cli/issues/154
to remove hardcoding and allow full input JSON to be provided
Removed hardcoding
> fix: removing hardcoded input table name in sasjs request

- package-lock.json
- package.json
- src/sasjs-context/create.js
- src/sasjs-context/edit.js
- src/sasjs-context/export.js
- src/sasjs-context/index.js
- src/sasjs-context/list.js
- src/sasjs-context/remove.js
- src/sasjs-servicepack/deploy.js
- src/sasjs-servicepack/index.js
- src/utils/file-utils.js
- test/commands/context/sasjs-context.list.spec.js
- test/commands/servicepack/sasjs-servicepack.deploy.spec.js
#140 
1. Cover with unit tests `sasjs servicepack` command.
2. Cover with unit tests `sasjs context` command.
1. Refactored code related to `sasjs servicepack` command.
2. Refactored code related to `sasjs context` command.
> test(sasjs-commands): covered 'servicepack' and 'context' commands

- src/sasjs-folder/create.js
> chore: help message for sasjs folder

- src/sasjs-build/index.js
Safely handled case when 'SAS Programs' are not defined.
1. Updated `getProgramList` function.
> fix(build): handled case when 'SAS Programs' are not defined

- src/sasjs-build/index.js
https://github.com/sasjs/cli/issues/163
Insert precode as part of the compile step rather than later in the process.
* Moved insertion of precode to `compile` step.
* Removed precode insertion at the time of creating the final `.sas` files.
> fix(sasjs-compile): insert precode as part of compile step

- src/sasjs-build/index.js
- src/utils/config-utils.js
- test/commands/cbd/sasjs-cbd.spec.js
- test/commands/cbd/testServices/serviceinit.sas
- test/commands/cbd/testServices/serviceterm.sas
closes #164 
Support jobs.
1. Updated `build` functionality.
2. Updated `cbd` functionality. 
3. Updated `config-utility` functionality.
> feat(jobs): added jobs support

- package-lock.json
- src/sasjs-build/index.js
- test/commands/cbd/sasjs-cbd.spec.js
Closes #210 
Leave the services in root, instead of in subfolder.
Changed the code that is creating json file content.
Someone else must run those, my environment doesn't work.
> fix: folder regression, services stay in the root

- .github/workflows/run-tests.yml
- jest.config.js
- package-lock.json
- package.json
- src/main.js
- src/utils/command.js
Fix unit test failure.
1. Fixed `cbd` command.
2. Set run tests sequentially rather than in parallel.
> fix(tests): fixed tests

- package-lock.json
- package.json
Updated sasjs adapter version.
> chore: updated sasjs adapter version

- src/commands/deploy.js
Wrong parameter passed to the `getAccessToken` function.
> fix: getAccessToken

- src/commands/help.js
- src/utils/command.js
- test/commands/folder/delete.spec.js
- test/commands/help.spec.js
closes #228 
Improve `sasjs help` command
`help.js` has been refactored.
> feat(help): help command has been improved

- package.json
Needed to run `npm link` on every change.
Update `start` command in package.json
Added `npm link` to  `start` command in package.json
> chore: Added 'npm link' to start

- package-lock.json
- package.json
Unable to contribute to CLI in windows, issue with building and linking of cli
Replace `cp` with `cp-cli`
[cp-cli](https://www.npmjs.com/package/cp-cli) installed along `tslib`
Copied *.json files separately in npm scripts `cp-json`
Replaced single quotes with escaped double quotes for windows in `package.json`
Also `--force` flag is required while `npm run start` for `npm link` in windows else it gives error
**Tested with CMD**, (watching, rebuilding and link)
Proof with Git-Bash and CMD
**Tested with Git-Bash**, (watching, rebuilding and link)
Proof with Git-Bash and CMD
> chore: contributing to CLI on windows

- .github/workflows/run-tests.yml
> chore(run-tests): deleted on push action

- package-lock.json
- package.json
- src/commands/flow/execute.ts
- src/commands/job/execute.js
closes #309 
closes #308
Fix `sasjs.startComputeJob` response handling.
1. Updated `@sasjs/adapter` version.
2. Updated flow execute logic.
3. Updated job execute logic.
> fix(job): fixed sasjs.startComputeJob response handling

- src/commands/flow/execute.ts
Fix truncated log files.
Updated `sasjs flow execute` logic.
> fix(flow): fixed truncated log

- package-lock.json
- package.json
- src/commands/add/add-credential.ts
- src/commands/add/input.ts
https://github.com/sasjs/cli/issues/338
Remove unnecessary code to simplify input handling.
Fixed places where `@sasjs/utils` input functions have been used:
* The functions now return the actual value instead of an object containing the value, so we don't need to pass in a field name.
* The functions handle all error scenarios internally, so we don't need to handle those in the CLI.
> fix(input): refactor input operations to use simpler APIs

- src/commands/flow/execute.ts
Catch uncaught promise rejection error.
Added catch blocks to asynchronous functions.
> fix(flow-execute): added catch blocks

- package-lock.json
- package.json
- src/commands/flow/spec/flow.spec.server.ts
- src/commands/job/execute.ts
- src/commands/job/spec/job.spec.server.ts
Improve job logging
- Updated `sasjs job execute` logic
- Fixed unit test for `sasjs job execute`
- Fixed unit test for `sasjs flow execute`
> feat(job): improved job logging

- package-lock.json
- package.json
- src/commands/version/spec/version.spec.ts
Fixes https://github.com/sasjs/cli/issues/393.
Improve dev experience by making rebuilds instant.
Remove unused dependencies.
* Removed `npm link --force` from the start script.
* Added `set:permissions` script that gives the built `index.js` file execute permission.
> chore(*): fix local build, remove unnecessary dependency

- package-lock.json
- src/commands/job/spec/job.spec.server.ts
- src/utils/spec/command.spec.ts
- src/utils/spec/displayResult.spec.ts
Fix setting `logger` in unit tests.
Mocked:
Server:
> chore(tests): fixed logger

- src/commands/shared/dependencies.ts
Fix warning message if dependencies were not found.
1. Updated `dependencies.ts`
Mocked:
Server:
> fix(dependencies): fixed warning message

- src/utils/config.ts
- src/utils/spec/config.spec.ts
Fixes https://github.com/sasjs/cli/issues/423.
Override env variable values with target-specific ones if available.
* Added `overrideEnvVariables` utility.
* Added tests.
> fix(env-override): prioritise variable values from target-specific env files

- package-lock.json
- package.json
- src/commands/add/addCredential.ts
- src/main.ts
- src/utils/auth.ts
- src/utils/command.ts
Closes #428 
Server response with _self signed certificate_ should be accepted if `--insecure` flag is present
Passed `insecure` boolean to adapter
Cli: mocked tests
Cli: server tests
> feat(add): make insecure request

- .vscode/launch.json
- src/commands/add/spec/add-credential.spec.ts
- src/utils/auth.ts
- src/utils/config.ts
- src/utils/file.js
https://github.com/sasjs/adapter/issues/212
* Improve file utils to use global logger.
* Fix typings for auth responses.
* Removed all `console.log`s in `file.js`.
* Fixed types in `add-credential.spec.ts`.
* Added debug configuration.
> fix(*): improve file utils, fix SasAuthResponse type

- src/commands/add/addCredential.ts
- src/commands/add/spec/add-credential.spec.ts
Closes #433 
Adding server url to target is breaking
parsed `target` with `target.json()`
> fix(add): parsing target with target.json()

- package-lock.json
- package.json
- src/commands/add/internal/input.ts
- src/types/configuration.ts
https://github.com/sasjs/utils/issues/22
Exit gracefully when input is cancelled.
* Upgraded to latest `@sasjs/utils`.
* Added `value` properties for choice objects.
> fix(cancel-input): exit gracefully when input is cancelled

- package-lock.json
- src/cli.spec.ts
- src/cli.ts
- src/commands/add/spec/add-target.spec.ts
- src/commands/build/build.ts
- src/commands/build/internal/config.ts
- src/commands/compile/compile.ts
- src/commands/compile/internal/checkCompileStatus.ts
- src/commands/compile/internal/config.ts
- src/commands/compile/internal/getAllJobFolders.ts
- src/commands/compile/internal/getAllServiceFolders.ts
- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/spec/compile.spec.ts
- src/commands/db/spec/db.spec.ts
- src/commands/deploy/deploy.ts
- src/commands/deploy/internal/getDeployScripts.ts
- src/commands/deploy/spec/cbd.spec.server.ts
- src/commands/deploy/spec/testConfig/config.json
- src/commands/docs/spec/generateDocs.spec.ts
- src/commands/flow/spec/flow.spec.server.ts
- src/commands/job/spec/job.spec.server.ts
- src/commands/request/spec/request.spec.server.ts
- src/commands/run/spec/run.spec.server.ts
- src/commands/shared/dependencies.ts
- src/config.json
- src/constants.ts
- src/utils/config.ts
- src/utils/test.ts
closes #429 
Standatize file paths of project assets.
Mocked:
Server:
> fix(paths): fixed file paths for project assets

- src/commands/docs/internal/getDocConfig.ts
- src/commands/docs/spec/generateDocs.spec.ts
- src/utils/config.ts
> fix: generate docs without target present

- src/commands/web/sasjsout.ts
Since moving to an appLoc/services/clickme location (instead of appLoc/clickme) the SAS html replace logic needs to be updated
> fix: appLoc issue in clickme

- package-lock.json
- src/commands/flow/execute.ts
- src/commands/flow/index.ts
- src/commands/flow/spec/flow.spec.server.ts
- src/commands/job/execute.ts
- src/commands/job/spec/job.spec.server.ts
closes #491 
Handle cases when a job was not found.
- updated `job execute` logic.
- updated `flow execute` logic.
Mocked:
Server:
> fix(job&flow): handled case when job was not found

- package-lock.json
- package.json
- src/commands/context/index.ts
1. Fix `validateConfigPath` in `context` command.
2. Bump @sasjs/adapter.
Mocked:
Server:
> Context fix

- package-lock.json
- package.json
Use the latest adapter's version.
> fix(depemdencies): bumped @sasjs/adapter

- package-lock.json
- package.json
> fix(dependencies): bumped adapter version

- package-lock.json
- package.json
Fix unhandled promise rejection in `sasjs flow execute` command.
> fix(dependencies): updated adapter version

- src/commands/add/addCredential.ts
- src/commands/add/addTarget.ts
- src/commands/add/internal/input.ts
- src/commands/add/spec/add-target.spec.ts
- src/commands/docs/internal/getDocConfig.ts
- src/commands/docs/spec/generateDocs.spec.ts
- src/commands/docs/spec/generateDot.spec.ts
- src/commands/request/request.ts
- src/commands/run/spec/run.spec.server.ts
- src/commands/servicepack/deploy.ts
- src/utils/config.ts
- src/utils/test.ts
Closes #541 
Refactor `findTargetInConfiguration` as per diagram
Resolve `sasjs add target` flow and update `findTargetInConfiguration`
mocked: 
server:
> fix(add): updating target and authorize for global

- package-lock.json
- package.json
> fix: bumping @sasjs/core version

- package-lock.json
- package.json
- src/commands/shared/createConfigFile.ts
- src/utils/test.ts
#6 
Fix warnings on @sasjs/cli install.
> Warnings issue

- package-lock.json
- package.json
updating @sasjs/lint to v1.2.0
> fix: updating sasjs/lint

- package-lock.json
- package.json
- src/commands/context/spec/context.spec.server.ts
- src/commands/docs/generateDocs.ts
- src/commands/flow/execute.ts
- src/commands/flow/spec/flow.spec.server.ts
- src/commands/flow/spec/testJob/largeLogJob.sas
- src/commands/job/spec/job.spec.server.ts
- src/commands/job/spec/testJob/largeLogJob.sas
- src/commands/servicepack/spec/servicepack.spec.server.ts
1) Bump @sasjs/adapter
2) improve unit test for `flow` and `job` commands
Mocked:
Server:
> fix: bumped adapter version and improved job and flow commands

- src/commands/web/index.ts
Resolve case, if `assetPaths` doesn't exists OR it's parent `webSourcePath` is not present
Handle case if any of `assetPaths` is not present and showing warning.
Also show warning if `webSourcePath` is not present
Updated `commands/web/index.ts`
> fix: handled code-breaking if assetsPaths does not exist

- .npmignore
Reduce package size by ignoring dev files.
Provided `.npmignore`.
> feat(npmignore): ignored dev files to reduce package size

- package.json
Configure pre-commit git hook only in git repository.
Added condition to `postinstall` script.
> fix(git-hook): fixed postinstall script

- package.json
Fix npm error if the current folder is not a git repository.
> fix(git-hook): fixed posinstall script

- package-lock.json
- package.json
- src/utils/config.ts
> fix(config): fixed case when url is an empty string

- .gitpod.dockerfile
- .gitpod.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
- src/commands/compile/compileSingleFile.ts
- src/commands/run/spec/run.spec.server.ts
Closes #6 
Avoid warnings on install - we've been waiting on a third party dependency to update their package
Bumped package.json, also added gitpod yaml files for easier cloud development
Mocked:
Server:
> fix: bumping jsdom, also adding .gitpod settings files

- package-lock.json
- package.json
- src/commands/compile/internal/compileTestFile.ts
closes #713 
Fixed regular expresion.
Mocked:
> fix(test-command): firxed macroTypeRegExp

- CONTRIBUTING.md
Updating CONTRIBUTING.md following developer session
> chore(CONTRIBUTING): adding Jest info

- package-lock.json
- package.json
- src/commands/deploy/deploy.ts
- src/commands/request/request.ts
- src/commands/run/run.ts
- src/commands/testing/index.ts
- src/utils/utils.ts
No linked issues.
Show 'runner not found' message with SAS code when the SASjs runner stored process is not found.
* Moved `sasjsRunnerCode` into utils function `displaySasjsRunnerError`.
* Called function in `deploy`, `run`, `request` and `test` command code.
Mocked:
Server:
> fix(runner-not-found-message): show message with SASjs runner code when process is not found

- package-lock.json
- package.json
- src/commands/request/request.ts
- src/commands/testing/index.ts
Use the latest version of `@sasjs/adapter`.
Used `jesJobExecutor` in `request` method of the `@sasjs\adapter`.
Mocked:
Server:
> fix(dependencies): fixed integration with @sasjs/adapter

- package-lock.json
- package.json
Fixes https://github.com/sasjs/cli/issues/811.
Address issue with 304 responses, access token expiry.
* Handle 304 responses correctly (in the adapter).
* Refresh access tokens if needed before making calls to the server.
> fix(*): address 304 issue, refresh tokens before server calls

- package-lock.json
- package.json
- src/commands/context/spec/context.spec.server.ts
- src/commands/flow/execute.ts
- src/commands/flow/index.ts
- src/commands/flow/spec/flow.spec.server.ts
- src/commands/job/execute.ts
- src/commands/job/index.ts
- src/commands/job/spec/job.spec.server.ts
> fix(startComputeJob): added terminate the process if adapter couldn't get session status

- src/commands/build/build.ts
- src/commands/web/index.ts
- src/commands/web/sasjsout.ts
sasjs web should be able to host web app with nested files.
Mocked:
Server:
> feat(web): process all files under webSourcePath nested

- src/commands/deploy/deploy.ts
- src/commands/request/request.ts
- src/commands/run/run.ts
- src/commands/testing/index.ts
> fix: global sas9 target shoud use authConfigSas9 property for credentials

- package-lock.json
- package.json
- src/commands/deploy/spec/cbd.spec.server.ts
- src/commands/run/spec/run.spec.server.ts
None.
Upgrade the CLI to the latest version of `@sasjs/adapter`.
* Upgraded `@sasjs/adapter` dependency.
Server:
> fix(deps): upgrade SASjs adapter

- src/commands/add/addCredentialCommand.ts
- src/commands/add/addTargetCommand.ts
- src/commands/build/buildCommand.ts
- src/commands/build/compileBuildCommand.ts
- src/commands/compile/compileCommand.ts
- src/commands/compile/compileSingleFileCommand.ts
- src/commands/context/createContextCommand.ts
- src/commands/context/deleteContextCommand.ts
- src/commands/context/editContextCommand.ts
- src/commands/context/exportContextCommand.ts
- src/commands/context/listContextCommand.ts
- src/commands/create/createCommand.ts
- src/commands/db/dbCommand.ts
- src/commands/deploy/compileBuildDeployCommand.ts
- src/commands/deploy/deployCommand.ts
- src/commands/docs/generateDocsCommand.ts
- src/commands/docs/generateDotCommand.ts
- src/commands/docs/initDocsCommand.ts
- src/commands/folder/createFolderCommand.ts
- src/commands/folder/deleteFolderCommand.ts
- src/commands/folder/listFolderCommand.ts
- src/commands/testing/testCommand.ts
- src/commands/version/versionCommand.ts
- src/commands/web/webCommand.ts
- src/types/command/commandBase.ts
> chore: yargs examples

- .github/workflows/run-tests.yml
Fixing vpn issue
Matching sources list with ubuntu on github
Mocked:
Server:
> chore: vpn fix

- .github/workflows/run-tests-windows.yml
- src/commands/compile/compileCommand.ts
- src/commands/web/spec/updateTagSource.spec.ts
> chore(ci): use linked version

- README.md
> fix(*): trigger release

- package-lock.json
Fixes #1006. 
Fix `semantic-release` issue.
Update package lock file to use previous version of `node-fetch`.
> fix(ci): fix issue with semantic-release success step

- package-lock.json
- package.json
- src/commands/add/spec/addTarget.spec.ts
- src/commands/job/internal/execute/viya.ts
- src/commands/job/internal/utils.ts
- src/commands/shared/fetchLogFileContent.ts
- src/commands/testing/test.ts
- src/utils/utils.ts
Closes #1067
Closes #313
- Improve logging when polling job/session state.
- Improve logging in `job execute` command.
- Removed extra logging from `executeJobViya` function.
- Removed extra logging from `saveLog` utility.
- Removed extra logging from `fetchLogFileContent` function.
- Fixed logging in `sasjs test` command.
Mocked:
Server:
> Improve logging in job execute and test commands

- package-lock.json
- package.json
- src/commands/compile/spec/compileJobFile.spec.ts
- src/commands/compile/spec/compileServiceFile.spec.ts
- src/commands/compile/spec/loadDependencies.spec.ts
Closes #1064 
Fix missing `initProgram` and `termProgram` for sasjs tests.
Mocked:
Server:
> fix(compile): fix missing termProgram in test files

- src/commands/web/internal/sasjsout.ts
fix: adding support for mp4, WOFF, WOFF2, TTF, GIF and JPEG  in sasjs/cli streaming app compilation
n/a
Streaming apps are not currently supporting the above mime types
update the SAS code
> fix: adding support for mp4, WOFF, WOFF2, TTF, GIF and JPEG 

- src/commands/help/help.ts
> fix: sasjs request help update

- src/commands/deploy/deploy.ts
No issue to link.
SASJS server deploys should also work with _Desktop Mode_ of server.
Calling deploy function, even if there's no authConfig is present.
Mocked:
Server(without `request.spec.server`):
> fix(deploy): can also deploy without auth on sasjs server

- src/commands/web/internal/getTags.ts
- src/commands/web/internal/spec/testFiles/script3.js
- src/commands/web/internal/spec/testFiles/style1.css
- src/commands/web/internal/spec/updateLinkTag.spec.ts
- src/commands/web/internal/spec/updateScriptTag.spec.ts
- src/commands/web/internal/spec/updateStyleTag.spec.ts
- src/commands/web/internal/updateAllTags.ts
- src/commands/web/internal/updateLinkTag.ts
- src/commands/web/internal/updateScriptTag.ts
- src/commands/web/internal/updateStyleTag.ts
Closes #1112 
Support video tags `<source>`
Support links in css
In addition to JS files, `<script>` are also being processed:
- `updateScriptTag` is updated
Video tags are supported:
- new function `getSourceTags` added
- and handled through `updateLinkTag`
In addition to external stylesheet tags i.e. `<link>`:
- added `getStyleInPageTags`
- and handled through `updateStyleTag `
Mocked:
Server(without `request.spec.server`):
> Supported more features to sasjs web

- src/commands/build/build.ts
closes #1081 
build command should place jobs in jobs folder rather than services
remove hard coded location from `getWebServiceScriptInvocation` function
Mocked:
Server (without `request.spec.server.ts`):
> fix: sasjs build is not recognising the jobs folder

- .github/workflows/npmpublish.yml
Fixing the node version in the release process
> fix: pinning release node version to avoid release errors

- package-lock.json
- package.json
none
bump adapter version
updated sasjs/adapter version to 3.7.3
> fix: bump adapter version

- package-lock.json
- package.json
- src/commands/add/addCredential.ts
- src/utils/auth.ts
Fixes #1136
Should handle such case and display error message on console.
Added check on accesstoken and refreshtoken if not present show error message.
Updated cli response:
> fix: display error message on not getting access tokens

- src/commands/testing/spec/mockedAdapter/testResponses.ts
- src/commands/testing/spec/testing.spec.ts
- src/commands/testing/test.ts
- src/utils/createSASjsInstance.ts
no issue to link.
Remove dependency of `SASJS` server for specs.
Update specs of testing using `SASJS` server.
Updated, test for both `SASJS` and `SASVIYA`.
Provided mocked responses
Removed deploy steps.
Converted `testing.server.spec.ts` to `testing.spec.ts`
> test: provided mock responses from server for SASVIYA + SASJS

- package-lock.json
- package.json
- src/utils/utils.ts
Runner not getting created in correct directory.  Also, usernames with embedded commas are breaking the mf_getuser() macro (used in some build scripts), fixed in https://github.com/sasjs/core/pull/191 and bumped here.
> fix: using &_metauser on runner and bumping core.  Closes #1147

- src/commands/add/internal/input.ts
closes #1146 
*  remove leading slash from serverUrl input
* `serverUrl.replace(/\/$/, '')`
> fix: remove trailing slash from serverUrl input

- package-lock.json
- package.json
- src/commands/add/addCommand.ts
- src/commands/add/addCredential.ts
- src/commands/add/spec/addCommand.spec.ts
- src/utils/auth.ts
no issue to link.
Adapter will throw error for not getting access token from server i.e. request being returned with 400 [adapter change](https://github.com/sasjs/adapter/pull/667)
Revert code for checking access token and throwing.
> fix(auth): adapter will throw if server responded with error

- package-lock.json
- package.json
- src/commands/request/request.ts
closes #1145 
* bump adapter version
* when there is an error from sas, no need to write output.json file just write logfile
> fix: sasjs request should not return json in log file

- src/commands/build/build.ts
- src/commands/deploy/deploy.ts
- src/commands/web/web.ts
sasjs/server [issue](https://github.com/sasjs/server/issues/80)
Should compile, build and deploy for Server Type `SASJS`
`build.ts`
- removed additional redundant nested function call
`deploy.ts`
- minimal changes 
`web.ts`
- minimal changes
> feat(cbd): stream app for sasjs server

- package-lock.json
- package.json
- src/commands/compile/compile.ts
- src/commands/compile/compileSingleFile.ts
- src/commands/compile/internal/compileTestFile.ts
- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/internal/spec/compileTestFile.spec.ts
- src/utils/displayResult.ts
Closes #1164
- Address compilation issue detected in `@sasjs/core`.
- Bumped `@sasjs/utils`.
- Fixed `CompileTree` usage in `compileTestFile`
Server:
> fix(compile): addressed compilation issue

- src/commands/testing/test.ts
- src/utils/config.ts
Closes #1168 
Fix coverage report issue in `@sasjs/core`, but the issue is not because of `@sasjs/cli`, but incorrect sasjs configuration in `@sasjs/core`.
- Refactored `src/commands/testing/test.ts`.
- Refactored `src/utils/config.ts`.
> chore(test-cmd): improve code readability

- package-lock.json
- package.json
- src/commands/deploy/deploy.ts
- src/commands/deploy/spec/cbd.spec.ts
sasjs/server [issue](https://github.com/sasjs/server/issues/91)
Add stream app related info(streamServiceName, streamWebFolder, streamLogo) in deploy request.
Passed streamConfig to sasjsdeploy function
> feat(deploy): to SASJS server with streaming app

- package-lock.json
- package.json
closes #1174
bump adapter version
> fix: failure of sasjs request with payload on sasjs server

- package-lock.json
- package.json
- src/commands/add/spec/addTarget.spec.ts
- src/commands/testing/internal/saveOutput.ts
- src/commands/testing/spec/mockedAdapter/testResponses.ts
- src/commands/testing/spec/testing.spec.ts
- src/commands/testing/test.ts
- src/types/index.ts
- src/types/testing.ts
- src/utils/test.ts
Closes #1101
- Fail test suite if at least one test failed.
- Adjusted logic related to logging test results.
- Add unit test covering such scenario.
> fix(testing): fail test suit if any test failed

- .github/workflows/run-tests.yml
- package-lock.json
- package.json
- src/commands/job/internal/execute/sasjs.ts
- src/commands/job/jobCommand.ts
- src/commands/job/spec/execute.spec.ts
- src/commands/request/request.ts
- src/commands/request/requestCommand.ts
- src/utils/displayResult.ts
#1198 
- `executeJob` function was missing `authConfig` parameter.
- `request` method wasn't returning an error when the access token missing - because we use the web approach which was waiting on login to resend the request.
- displayError function was broken if only error message was provided.
> request and job execution on sasjs server mode auth handling

- package-lock.json
- package.json
- Bumping up @sasjs dependencies
> sasjs dependencies bump

- package-lock.json
- package.json
- src/commands/compile/compile.ts
- src/commands/compile/internal/compileFile.ts
> fix: compilation using source folder instead of sasjsbuild

- package-lock.json
- package.json
- src/commands/compile/compile.ts
- src/commands/compile/internal/copySyncFolder.ts
Fixes #1209 
Should be able to copy files from syncFolder of `Configuration.Root` and then of `Target`.
> feat(compile): able to sync folder after compile

- package-lock.json
- package.json
https://github.com/sasjs/core/issues/263
Enabling SYSENCODING in output per https://github.com/sasjs/core/issues/263
Bumping sasjs/core library
> fix: bumping core to enable sysencoding in `webout()`

- package-lock.json
- package.json
- src/commands/compile/internal/compileFile.ts
- src/commands/deploy/spec/cbd.spec.ts
Note - downstream projects will also need to bump core in order to get the latest mX_webout underlying macro.
Closes #1236
#1236 
Enable the SAS developer to choose the max number of observations to send back in the response JSON
Added MAXOBS option to webout in a similar fashion to this PR:  https://github.com/sasjs/core/pull/294
> feat: adding MAXOBS param in webout macros, and bumping core.

- .github/workflows/run-tests-windows.yml
- .github/workflows/run-tests.yml
- package-lock.json
- package.json
- src/commands/run/run.ts
- src/commands/run/runCommand.ts
- src/commands/run/spec/run.spec.server.sasjs.ts
- src/commands/run/spec/testServices/logJob.js
- src/commands/testing/test.ts
- src/utils/test.ts
closes #1241
* add support for executing `sasjs run` command on sasjs server
implemented logic for running code on sasjs server.
> feat: execute 'sasjs run' for sasjs server

- CONTRIBUTING.md
- package-lock.json
- package.json
- src/commands/add/internal/input.ts
- src/commands/deploy/deploy.ts
closes #1249
* bump sasjs/utils version that has fix for `deployServicePack` should be true by default
* log error to console when the script is not executed from sasjs deploy command
> fix: update @sasjs/utils version

- .github/workflows/run-tests.yml
- src/commands/help/help.ts
- src/commands/run/run.ts
- src/commands/run/runCommand.ts
- src/commands/run/spec/runCommand.spec.ts
- src/utils/saveLog.ts
Closes #1251 
- sasjs run command - added `--log` parameter.
> Issue 1251

- src/commands/help/help.ts
- src/commands/job/internal/execute/sas9.ts
- src/commands/run/run.ts
- src/commands/run/runCommand.ts
- src/commands/run/spec/runCommand.spec.ts
- src/utils/parseSourceFile.ts
- src/utils/utils.ts
Closes #1253
- Added `--source` flag to the `run` command.
> Added --source flag to run command. 

- package-lock.json
- package.json
n/a
Bump macro core and sasjs lint
Updated versions in package.json
> fix: bumping core and lint

- package-lock.json
- package.json
> fix: bump @sasjs/utils version

- package-lock.json
- package.json
- src/commands/compile/spec/compileCommand.spec.ts
- src/commands/deploy/spec/utils.ts
- src/types/command/targetCommand.ts
- src/utils/config.ts
Closes #1234 
- Fix getting target from config.
- Bumped `@sasjs/utils`.
- Fixed unit tests covering `compileCommand`.
- Fixed `findTargetInConfiguration` function by providing a higher-level target to `Target` constructor.
> fix(cb): fixed findTargetInConfiguration

- src/commands/build/compileBuildCommand.ts
- src/commands/build/spec/compileBuildCommand.spec.ts
- src/commands/compile/compileCommand.ts
- src/commands/compile/spec/compileCommand.spec.ts
- src/commands/deploy/compileBuildDeployCommand.ts
- src/commands/deploy/spec/compileBuildDeployCommand.spec.ts
Closes #1285
- Improve logging in `compile` command.
- Added `target` and `serverType` to the logging in `CompileCommand`, `CompileBuildCommand` and `ompileBuildDeployCommand`.
- Adjusted unit tests.
> feat(compile): improved logging

- package-lock.json
- package.json
- src/commands/fs/fsCommand.ts
- src/commands/fs/spec/fsCommand.spec.ts
it will compile and deploy a local directory tree on a remote SAS server.
> feat: add new command 'sasjs fs deploy'

- src/commands/shared/deployToSasViyaWithServicePack.ts
> fix: convert base64 encoded content to binary before deploy

- src/commands/web/internal/getTags.ts
- src/commands/web/internal/spec/updateSasjstag.spec.ts
- src/commands/web/internal/updateAllTags.ts
- src/commands/web/internal/updateSasjsTag.ts
- src/commands/web/web.ts
closes #1183
* Auto-configure serverType and appLoc in sasjs web
> feat: Auto-configure serverType and appLoc in sasjs web

- package-lock.json
- package.json
- src/commands/deploy/internal/executeDeployScriptSasViya.ts
- src/config.json
- src/utils/spec/setConstants.spec.ts
closes 31176
* update config file created after running `sasjs create`
* fix specs
* bump @sasjs/adapter
> fix: issues in deployment after sasjs create

- src/commands/deploy/internal/executeDeployScriptSas9.ts
> fix(typo): use password instead of username

- package-lock.json
- package.json
- src/commands/testing/internal/saveOutput.ts
> fix: bump csv-stringify and sasjs/lint

- package-lock.json
- package.json
- src/commands/deploy/internal/executeDeployScriptSas9.ts
- src/commands/request/request.ts
> fix: show proper runner error when runner is missing on sasjs deploy and sasjs request

- src/commands/docs/generateDocs.ts
closes #1331
There should be no Lineage tab in the bar, nor Lineage link in the left-hand links box when enableLineage is set to be false.
> fix: hide lineage tab/link when enableLineage is false

- package-lock.json
- package.json
The was an issue related to packaged `@sasjs/adapter`.
Bump `@sasjs/adapter` version.
Updated `package.json` and `package-lock.json`.
> fix(adapter): fixes refresh token

- src/commands/create/spec/angularAppFiles.ts
- src/commands/run/spec/run.spec.server.viya.ts
> chore: cleanup

- src/commands/add/addCommand.ts
- src/commands/add/addCredential.ts
- src/commands/add/spec/addCommand.spec.ts
- src/utils/auth.ts
- Improve error message for `sasjs auth` command.
- Moved error handling from `src/commands/add/addCredential.ts` to `src/utils/auth.ts`.
- Adjusted unit tests.
> feat(auth): improved error message

- .github/workflows/npmpublish.yml
Github token is expired.
- Use regenerated Github token.
- Updated `.github/workflows/npmpublish.yml`.
- [] All CI checks are green.
> chore(npmpublish): fixed GITHUB_TOKEN

- .env.example
adding a VERBOSE= example
n/a
show a verbose example in the .env.example
added VERBOSE=off
> chore: Update .env.example

- package-lock.json
- package.json
> fix: bumping sasjs/core
