- src/utils/utils.js
Previously we did not have a `package.json` in the `minimal-seed-app` project, so there was no need to run an `npm install` when creating an app using the `minimal` template.
Since that has been added, we now need to run an install step when creating an app.
This change removes the third parameter to `createApp` which is an `installDependencies` flag that is `true` by default.
> fix(sasjs-create): install dependencies when creating minimal app

- src/sasjs-context/index.js
- src/utils/config-utils.js
- test/config-utils.spec.js
* Read `access_token` from environment if it wasn't found in the target configuration.
* Improve error parsing logic - this currently fails when the returned error body is not JSON.
We now show the parse error along with the original error like so:
> fix(sasjs-context): read access token from environment

- test.sh
Fixes https://github.com/sasjs/cli/issues/106
Test output escape sequences are rendered as plain text on `zsh` and other terminals when running locally.
This needs to be fixed so that the output is readable.
* Used `$'` notation for strings with escape sequences.
NB: This causes a `$` sign to be shown before each command in the GitHub Actions output, but that's still a fair compromise for being able to read the output locally.
> chore(ci): correct test output escape sequences

- README.md
- package-lock.json
- package.json
- src/cli.js
- src/main.js
- src/sasjs-context/index.js
- src/sasjs-folder/create.js
- src/sasjs-folder/index.js
- src/sasjs-folder/move.js
- src/sasjs-folder/remove.js
- src/sasjs-help/index.js
- src/utils/config-utils.js
closes #73 
Add file management commands.
> feat(file-management): added 'create', 'delete' and 'move' file commands

- src/sasjs-web/index.js
- src/sasjs-web/sasjsout.js
Fix base64 encoding of *.js and *.css files when streaming to SAS 9.
Updated 'getWebServiceContent' function and 'sasjsout' file.
> fix(web): fixed base64 encoding of *.js and *.css files

- src/utils/config-utils.js
- test/config-utils.spec.js
closes #119 
Sanitize `appLoc`.
Added `sanitizeAppLoc` function and used it in `getBuildTargets` and `getTargetToBuild` functions.
> chore(appLoc): added 'appLoc' sanitation

- package-lock.json
- package.json
- src/sasjs-run/index.js
- src/utils/utils.js
- test/sasjs-run.spec.js
- test/utils.spec.js
Fixes https://github.com/sasjs/cli/issues/128.
Improve the `sasjs run` command to address the issues described in https://github.com/sasjs/cli/issues/128.
* Migrated to the access token mechanism used by the other commands - fetch it from the `.env` file.
* Saved execution log to a `sasjs-run-{timestamp}.log` file.
> fix(sasjs-run): Change access token mechanism, store log to file

- src/utils/config-utils.js
- test/config-utils.spec.js
- test/utils.spec.js
Fixes https://github.com/sasjs/cli/issues/130.
Make `sasjs run`(and any other command that depends on `getAccessToken()` work with targets from the global `.sasjsrc` file.
* Use access token, refresh token, client and secret from global target if available.
* Use refresh token to automatically refresh access token if expiring.
* When refresh token is unavailable, use existing mechanism that requires manual intervention.
* Add unit tests.
> fix(sasjs-run): add the ability to execute sasjs run against a global target

- .github/workflows/run-tests.yml
- package.json
- src/sasjs-add/index.js
- src/sasjs-servicepack/index.js
- src/utils/input-utils.js
* Fixes https://github.com/sasjs/cli/issues/134.
* Fixes https://github.com/sasjs/cli/issues/135.
* Allow users to specify an appLoc when adding a target to the global `.sasjsrc` file.
* Check code style as part of CI builds
* Removed check that allows appLoc only for local targets.
* Added lint script and added build step to run it.
Unit test was unable to be added as it is currently impossible to mock two functions from the same module if they call each other. https://github.com/facebook/jest/issues/936
> AppLoc for global targets, code style checks in CI builds

- src/sasjs-build/index.js
- src/sasjs-deploy/index.js
- src/sasjs-web/index.js
- src/utils/config-utils.js
- test/commands/servicepack/sasjs-servicepack.deploy.spec.js
Fixes https://github.com/sasjs/cli/issues/157.
Look for target in global`.sasjsrc` if not present in local configuration.
* Use `findTargetInConfiguration` which already implements the expected behaviour.
* Remove redundant function `findTargetToBuild`.
(Unable to add a unit test due to issues with mocking out functions from the same module as the one being tested)
> fix(targets): use a single function to fetch target from configuration

- package-lock.json
- package.json
- src/main.js
- src/sasjs-build/index.js
- test/commands/compile/getDependencyPaths.spec.js
Handle cases when the dependency source is not present.
1. Updated error handling in `main.js`.
2. Changed `sasjs-build` logic.
3. Updated `getDependencyPaths.spec.js` test.
> fix(sasjs-cb): handled cases when dependency source is not present

- src/sasjs-build/index.js
- src/utils/file-utils.js
- test/commands/compile/example-reversed.sas
- test/commands/compile/getProgramDependencies.spec.js
- test/commands/compile/newlines.sas
- test/commands/compile/spacing.sas
https://github.com/sasjs/cli/issues/203
Improve the file header parsing mechanism and make it common between dependencies and SAS programs.
* Added `getList` function.
* Used `getList` function when parsing dependencies and SAS programs.
* Added tests for weird spacing scenarios.
> fix(sasjs-compile): make file header parsing more resilient

- src/sasjs-build/index.js
- test/commands/compile/loadDependencies.spec.js
https://github.com/sasjs/cli/issues/215
* Load dependencies for `init` and `term` files as part of the compile process.
* Call `getDependencyPaths` separately for `init`, `term` and actual file.
> Service dependencies

- src/cli.js
Closes #221 
Bash breaks Windows tools by replacing forward slash with a directory path
POSIX path conversion: http://www.mingw.org/wiki/Posix_path_conversion
Written regex to replace if /git/ path is pre appended in args in cli.js file
> fix: sasjs job execute issue for git-bash windows

- src/utils/utils.js
- test/removeComments.spec.js
Attempt to fix regression from fix to #209. 
Handle CRLF and LF line endings when removing comments from a file.
* Return empty string when input is falsy.
* Convert all CRLF line endings to LF before processing a file.
* Trim the end of each line to remove trailing spaces or line terminators.
* Added tests to cover line endings and formatting.
> fix(line-endings): handle CRLF line endings when removing comments

- src/cli.js
- src/constants.js
- src/sasjs-job/execute.js
#229
Cater cater case in Windows, Paths are with forward slash
Added OS specific slash constant `slashInPath`, use this in all command files, wherever `path` utility is used
Update: now we are using  `path.sep` provided by utility itself
> fix(win-path): delimiter in path slash OS specific

- src/sasjs-folder/index.js
- test/commands/folder/delete.spec.js
Fixes https://github.com/sasjs/cli/issues/234.
Support relative and absolute paths in `sasjs folder delete` command.
* Prepend `appLoc` to folder paths that don't start with a `/`.
> fix(sasjs-folder-delete): support relative and absolute paths

- src/sasjs-folder/index.js
- src/sasjs-folder/remove.js
- test/commands/folder/delete.spec.js
#234 was merged before checks passed.
Fix failing tests for `sasjs folder delete`.
* Generate configuration using timestamp.
* Fix `sasjs folder` command to wait for operation to complete.
* Mock `remove` module in tests.
> fix(sasjs-folder-delete): wait for operation to complete, fix tests

- src/sasjs-build/index.js
Fixes https://github.com/sasjs/cli/issues/237.
Remove unnecessary false warnings when compiling SAS program dependencies.
* Build up a list of found filenames.
* Check against list of all filenames and log the unfound filenames in a warning.
> fix(sas-programs): report on missing dependencies after checking all program paths

- src/commands/build.js
- test/helpers.js
Fixes https://github.com/sasjs/cli/issues/241
Fixes https://github.com/sasjs/cli/issues/248
Recognise global targets when they are named in `sasjs build -t <target-name>`.
* Pass `targetName` to `compile()` function.
* Check jobs against `buildDestinationFolderJobs` when determining if a project has already been compiled.
* Check for existing targets with the same name in the unit tests when adding new targets.
> fix(sasjs-build): recognise global targets, fix compile-build logic

- src/commands/help.js
- src/commands/job/execute.js
- src/utils/utils.js
- test/commands/job.spec.js
- test/utils.spec.js
Closes #193 
Log output for job should be plain text, not json.
> fix: job log extension changed to .log

- src/commands/deploy.js
- src/commands/servicepack/deploy.js
- src/main.js
https://github.com/sasjs/cli/issues/261
Fix `sasjs deploy` erroring out when the credentials are available in a local `.env` file.
* Get access token from the `.env` file.
* Only error out when the access token is unavailable.
* Improved error messages for compile and deploy functions.
> fix(sasjs-deploy): get access token from environment

- .github/workflows/assign-reviewer.yml
- .prettierrc
- package-lock.json
- package.json
- src/cli.js
- src/commands/job/execute.js
- src/commands/job/index.js
- src/utils/command.js
- test/commands/cbd/testJob/failingJob.sas
- test/commands/job.spec.js
- test/utils.spec.js
- test/utils/command.spec.js
Closes #250 
To update `--log` flag, `--output` flag's behavior and add new `--status` flag
++ handle absolute paths for `output`, `logfile` and `status`
++ handle `~` for win paths
++ use default context if not specified
Updated command utility:
- for `--log` flag updated to `--logFile` and alias are working i.e. `--log` and `-l`
- to have another flag `--status`
Update job execute code to have `status: success` in output file in case of `wait` and print on screen.
tested with unreleased adapter 
- checkout branch `issue250`
- `npm install`
- `npm link`
- verify with `npm -v` it should give you the path of local repository of sasjs-cli
_You are using a linked version of SASjs CLI running from sources at 1.0.0   {PATH}_
> fix(job flags): --log, --output and new --status

- .github/workflows/npmpublish.yml
- .github/workflows/run-tests.yml
- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
https://github.com/sasjs/cli/issues/274
Add TypeScript to CLI project.
* Added `TypeScript` and `@types/node` dependencies.
* Added `tsconfig.json`.
* Tweaked build and release process. 
Since adding TypeScript, there's now an extra build step to run the CLI locally from sources.
So after this PR is merged, you should pull from `main` and:
* `npm unlink`
* `npm ci`
* `npm run build`
* `npm link`
After this, you'll need to build it each time you make a code change.
> chore(*): add typescript to project

- .gitignore
- nodemon.json
- package-lock.json
- package.json
- src/index.ts
- test/commands/job.spec.js
https://github.com/sasjs/cli/issues/274
Bump adapter to be able to use type declaration files.
Watch for `.ts` file changes and rebuild.
* Added `nodemon` configuration.
* Upped adapter version
> fix(*): upgrade adapter to work with TypeScript

- src/commands/add.js
- src/commands/build.js
- src/commands/db.js
- src/commands/deploy.js
- src/commands/servicepack/deploy.js
- src/commands/web/index.js
- src/constants.js
- src/main.js
- src/utils/config-utils.js
- src/utils/utils.js
- test/commands/add.spec.js
- test/commands/build.spec.js
- test/config-utils.spec.js
Closes #291 
`build` looks for valid compile present in order to skip `compile` step
valid compile has checks for services folder + jobs folder
updated valid compile code
added extra check for compile to have either jobs or services folders in source
added tests for `build` and `cb`(skipping build)
updated constants file to have updated projectDir for `build` to work in their folders
updated `setupNpmProject` same as `setupGitIgnore` relative path covered in tests
updated `getRootFolder` folder, if already in root, as we run tests in our sasjs/cli/<test-folder-name>
updated `web` as well we are also using during `build` if `streamWeb` is true ( is case of [fileUploader](https://github.com/sasjs/fileuploader/))
> fix(build): valid compile + tests

- src/commands/deploy.js
- src/utils/utils.js
- test/commands/build.spec.js
- test/commands/cbd/cbd.spec.js
- test/commands/cbd/testConfig/config.json
- test/commands/cbd/testScript/copyscript.sh
Closes #297 
while deploying through deploy script, it is throwing error for not having `access_token`, which is not required
removed `access_token` requirement check from deploy in all cases.
Getting `access_token` throws error itself if not found, replaced better console message.
Written couple of tests for `deploy` (`cbd`), by creating new app, having it's own `sasjsconfig.json`, changes made to `src` related for these tests.
> fix(deploy): no need of access_token in all cases

- src/utils/config-utils.js
- test/utils/config-utils.spec.js
https://github.com/sasjs/cli/issues/327
Read `CLIENT`, `SECRET` and `REFRESH_TOKEN` from env variables.
Read `CLIENT`, `SECRET` and `REFRESH_TOKEN` from env variables if not available as part of the target's `authInfo` - this will make it work for local as well as global targets.
> fix(env-vars): get client, secret and refresh token from env vars

- .github/reviewer-lottery.yml
- src/commands/add/add-credential.ts
- src/commands/add/add-target.ts
- src/commands/add/config.ts
- src/commands/add/input.ts
- src/utils/file.js
- test/commands/add-credential.spec.ts
Fixes https://github.com/sasjs/cli/issues/342.
Save target URL in target configuration when adding credentials to a local target.
* Saves local `sasjsconfig.json` when adding credentials.
* Added test that captures the behaviour of saving the server URL if missing.
> fix(add-cred): save server URL when adding credentials to a local target

- src/commands/build.js
- src/utils/utils.js
- test/commands/add-target.spec.ts
- test/commands/create.spec.ts
Closes #321 
Remove `curl`'s only existence from code, it requires certificates to be configured. Some users have issue on windows with portable git-bash
removed `curl` (calling github api), replaced with `git ls-remote`
To test:
checkout branch `issue321` and `npm start`
> fix(create): fetching template info without curl

- package-lock.json
- package.json
- src/commands/deploy/deploy.ts
- src/utils/config.ts
Fixes https://github.com/sasjs/cli/issues/390
Fixes https://github.com/sasjs/cli/issues/389
Fixes another unlisted issue with log parsing when a deploy fails
Remove warnings when there are no program folders specified.
Ignore null or undefined server URL.
Fix error when deploy script fails.
* Removed warnings.
* Set `debug` to true in the adapter instance.
* Bumped version of `@sasjs/utils`.
> fix(*): Program folder warnings, Undefined Server URLs

- package-lock.json
- package.json
- src/commands/add/addCredential.ts
- src/commands/add/addTarget.ts
Fixes https://github.com/sasjs/cli/issues/399
Save auth config correctly when authenticating against a global target.
* Convert target to JSON before saving.
* Bump `@sasjs/utils` to fix saving of server-specific attributes like `contextName`.
> fix(*): fix saving of global targets after authentication, add server-specific attributes to target JSON

- src/commands/build/build.ts
No issue raised.
When deploying using the generated `.sas` file, the services are deployed at the root and not in a `services` subfolder.
This needs to be fixed to deploy to the correct folder.
* Added `/services` to service paths
> fix(build): prepend `/services` folder to service paths

- .prettierrc
- src/commands/flow/execute.ts
- src/utils/file.js
- src/utils/spec/file.spec.ts
1. Fix log link for Windows.
2. Fix creating files on Windows.
1. Updated `flow execute` logic.
2. Updated `createFile` utility.
Mocked:
Server:
> fix(flow-execute): fixed log link for Windows

- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/spec/getDependencyPaths.spec.ts
- src/commands/shared/dependencies.ts
Fixes https://github.com/sasjs/cli/issues/405
Load overridden macros only once regardless of OS platform.
* Used `path.sep` instead of hardcoded `/` when checking file paths for overrides.
> fix(sasjs-compile): Prevent duplicate dependencies with windows file paths

- src/commands/add/addTarget.ts
- src/commands/build/build.ts
- src/commands/compile/compile.ts
- src/commands/context/list.ts
- src/commands/db/db.ts
- src/commands/deploy/deploy.ts
- src/commands/flow/execute.ts
- src/commands/flow/index.ts
- src/commands/flow/spec/flow.spec.server.ts
- src/commands/folder/move.ts
- src/commands/job/execute.ts
- src/commands/run/run.ts
- src/commands/servicepack/deploy.ts
- src/types/file.ts
- src/types/index.ts
- src/utils/config.ts
- src/utils/file.js
- src/utils/spec/file.spec.ts
- src/utils/spec/utils.spec.ts
- src/utils/utils.ts
closes #349
1. Provide absolute file paths to the `logs` and `csv` files.
2. Save `csv` file to the default location if the location was not provided. 
3. Format timestamp in log file name.
4. Fix trailing dot in CLI output.
Mocked:
Server:
> fix(*): fixed linkes to files

- src/commands/docs/generateDocs.ts
- src/commands/docs/initDocs.ts
- src/commands/docs/internal/getFoldersForDocs.ts
- src/commands/docs/internal/getFoldersForDocsAllTargets.ts
- src/commands/docs/spec/generateDocs.spec.ts
- src/config.json
- src/main.ts
- src/types/configuration.ts
Closes #415 
Should document macroCore from `node_modules` conditionally.
Added `DocConfig` to `Configuration` based on it, either @sasjs/core will be added/excluded in `sasjs doc`
+ outDirectory can also be mentioned in `DocConfig`, but command line param has precedence.
> feat: document macroCore as well

- src/cli.ts
`sasjs compile` is not working
Found issue is due to `process.projectDir` was not set, behavior was changed in [PR](https://github.com/sasjs/cli/pull/453/files)
Updated `cli.js` only
> fix: process.projectDir needed for other commands

- package-lock.json
- package.json
- src/commands/build/build.ts
- src/commands/compile/compile.ts
- src/commands/compile/spec/compile.spec.ts
- src/commands/db/db.ts
- src/commands/deploy/deploy.ts
- src/commands/web/index.ts
- src/main.ts
- src/utils/file.js
https://github.com/sasjs/cli/issues/471
Fix references to JS and CSS files in generated web app output.
* Added `/services` to file paths in tag hrefs.
* Made `streamServiceName` configurable from `streamConfig`.
* Fixed formatting on deploy logs.
* Showed web app URL on terminal after deployment.
* Removed noise from terminal output by changing `logger.info` to `logger.debug` where applicable (more left to do on this front).
* Removed more noise from terminal output by fetching the target once, and then reusing across compile, build and deploy steps.
> fix(sasjs-web): fix service paths in generated web app HTML

- src/commands/web/sasjsout.ts
For streaming apps the "clickme" (or whichever name is configured in the [streamConfig](https://cli.sasjs.io/sasjsconfig.html#targets_items_anyOf_i0_streamConfig) is deployed under the services subfolder.
We can use this to auto-detect the appLoc by reference to the _program variable.
This commit fixes the fix that was supposed to address the move from appLoc/{clickme} to /apploc/services/{clickme}
> fix: appLoc finder with comment

- src/commands/docs/generateDocs.ts
docs header is not populating well with project's description
For template jobs, we having following description
- "description": "The template used by SASjs when running `sasjs create myProject -t jobs`",
While passing description to doxygen-cli, it executes `sasjs create myProject -t jobs`.
Escaped description string and prevent execution
> fix(docs): escaping param and prevent from executing command

- package-lock.json
- package.json
- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/spec/compile.spec.ts
- src/commands/compile/spec/loadDependencies.spec.ts
- src/commands/compile/spec/services/example.sas
- src/commands/shared/dependencies.ts
1. Closes #439 
2. Closes #434 
1. Instead of showing warning, show error and stop execution
2. get program dependencies from init/term for job/service and add to all jobs/services
1. Logger's warning turned into Error. also displaying `programFolders` in bullet list
2. Extracted `init`/`term` for `job`/`service` same way as currently for `job`/`service`, and place at the start of dependencies section.
Applicable to below files
- jobInit
- jobTerm
- serviceInit
- serviceTerm
> halt on missing sas program + init/term support for programs

- src/utils/file.js
Fixes https://github.com/sasjs/cli/issues/496.
Fixes https://github.com/sasjs/cli/issues/516.
Alleviate any confusion caused by file access errors being displayed in the terminal.
* Removed `logger.error` from `readFile` - the error is always going to be caught upstream.
> fix(read-file): remove unnecessary error log

- src/commands/compile/internal/config.ts
- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/spec/getProgramDependencies.spec.ts
- src/commands/compile/spec/loadDependencies.spec.ts
- src/commands/shared/dependencies.ts
In `sasjs compile`, while getting programDependencies, we are now throwing error for not getting dependency in listed program folders. Also need to display source file name in main error.
Display file name along error message for missing dependency
Changed `getProgramDependencies` in _src/shared/dependencies.ts_, passed `filePath` to it.
Also getting programDependencies for `init`/`term`, needed their paths, so updated following functions in _src/compile/internals/config.ts_
- `getServiceInit`
- `getServiceTerm`
- `getJobInit`
- `getJobTerm`
mocked: 
server:
> fix(compile): show file name in error when getting programDependencies

- src/commands/build/internal/config.ts
- src/commands/compile/compile.ts
- src/commands/compile/compileSingleFile.ts
- src/commands/compile/internal/checkCompileStatus.ts
- src/commands/compile/internal/compileJobFile.ts
- src/commands/compile/internal/compileServiceFile.ts
- src/commands/compile/internal/config.ts
- src/commands/compile/spec/compile.spec.ts
- src/commands/compile/spec/compileJobFile.spec.ts
- src/commands/compile/spec/compileServiceFile.spec.ts
- src/commands/context/index.ts
- src/commands/deploy/deploy.ts
- src/commands/docs/internal/getFoldersForDocs.ts
- src/commands/index.ts
- src/commands/job/spec/job.spec.server.ts
- src/commands/request/request.ts
- src/commands/run/run.ts
- src/commands/servicepack/deploy.ts
- src/commands/shared/dependencies.ts
- src/commands/web/index.ts
- src/main.ts
- src/utils/command.ts
- src/utils/test.ts
Closes #469 
Closes #486 
Compile single job/service.
And to support absolute paths wherever possible
Code refactored:
- extracted code from compile to internals, `compileServiceFile.ts` and `compileJobFile.ts`
- used these to newly introduced command file `compileSingleFile.ts`
Fix in context index.ts
`command.ts` utility updated accordingly to new supported flags for subcommand(`job` and `service`)
changed `path.join` to if `path.isAbsolute` use it else use `path.join`
> feat(compile): compile single job/service

- package-lock.json
- package.json
- src/commands/add/addCredential.ts
- src/commands/add/addTarget.ts
- src/commands/add/internal/input.ts
- src/commands/add/spec/add-target.spec.ts
- src/types/commonFields.ts
- src/utils/auth.ts
- src/utils/config.ts
Closes #332
Closes #500 
Closes #495
- If target is specified in any `sasjs <command>`, and not found it should stop and do not fall back to first.
- if target name is not specifed in any `sasjs <command`, then fallback message should be _INFO_ not _WARN_
- While `sasjs add target`, if specified `targetName` is found, instead of giving error, show option to update this `target`
Error throw in `findTargetInConfiguration`, if targetName is provided and not found and changed logger warning -> info
`getCommonFields` in `addTarget.ts` is changed and also returns `existingTarget`, added new user input `getAndValidateUpdateExisting`
`add-target.spec.ts` is refactored and added more tests to it.
mocked: 
server:
> fix: throw error if target not found with name

- src/commands/web/index.ts
- src/commands/web/spec/web.spec.ts
- src/main.ts
- src/utils/config.ts
- src/utils/test.ts
Closes #553
`StreamConfig` should be inherited to target from root level, for all actions in `sasjs web`
Also resolve _unhandled promise rejections_ in `main.ts`
- Updated `main.ts`,  `unhandled promise rejections` were due to `findTargetInConfiugaration`.
- Passed down inherited `StreamConfig` to all actions in _src/commands/web/index.ts_
- Added test for `sasjs web`, with configuration having `streamConfig` at root level and not at target.
> fix: inherit streamConfig for building web app

- src/commands/compile/spec/compile.spec.ts
- src/constants.ts
Instead of having multiple folders in home directory( ~/sasjsbuild/ and ~/sasjsresults/), need to have ~/.sasjs/ and have both directories in it.
Updated `src/constants.ts` and tests
> fix: have single home directory .sasjs for sasjsbuild & sasjsresults

- src/commands/docs/generateDocs.ts
- src/commands/docs/internal/createDotFiles.ts
- src/commands/docs/internal/getDotFileContent.ts
- src/commands/docs/spec/generateDot.spec.ts
- src/commands/docs/spec/testJobHavingBackSlashes/runjob2.sas
- src/commands/docs/spec/testJobHavingDoubleQoutes/runjob1.sas
Closes #578
Support case-insensitive filename for doxygen configuration, currently its `Doxyfile`
`sasjs doc`  should not fail when @brief attribute contains double quotes
doxygen configuration filename should be case-insensitive
Updated `createDotFiles.ts` 
- Added try catch for future unknown errors
- Added file creation logger messages
Updated `getDotFileContent.ts `
- embedded quotes escaped before writing to DOT file
> fix(doc): support case-insensitve filename for 'doxyfile' + escaping double qoutes & escape characters

- src/commands/docs/generateDocs.ts
Need to see additional info why doxygen failing 
If logger level is `Debug`,  showing complete doxygen output from `shelljs` execution
`generateDocs.ts` updated, spinners also stopped if showing shelljs output
> fix(docs): show full doxygen log for logger level debug

- package-lock.json
- package.json
- src/commands/job/spec/job.spec.server.ts
- src/commands/lint/index.ts
- src/commands/run/run.ts
- src/commands/run/spec/run.spec.server.ts
Move CLI logic related to lint moved to utils/lint
- utils/lint version updated
- removed code from `lint/index.ts`, because logic is moved to `utils/lint`
> fix: utils/lint version updated + removed cli logic for lint

- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/spec/loadDependencies.spec.ts
- src/commands/shared/dependencies.ts
- src/main.ts
Closes #593
Closes #584 
Switch `<h4> SAS Programs </h4>` to `<h4> SAS Includes </h4>`
and show link to index.html in console for `sasjs doc`
Updated `compile/internal/loadDependencies.ts`
- Added `info` till 6 six months
- Added `warning` after 6 months and till 1 year
Updated `shared/dependencies.ts`
- Added check to load `<h4> SAS Includes </h4>` along `<h4> SAS Programs </h4>`
> feat: Switch <h4> SAS Programs </h4> to <h4> SAS Includes </h4>

- package-lock.json
- package.json
- src/commands/build/build.ts
The previous version of @sasjs/core used a different git hooks library that left a message in the install console.  The new one leaves no unnecessary message.
> fix: updating core library

- src/commands/compile/compileSingleFile.ts
Fix compiling of single file. It breaks when deleting current output folder
`path.sep` is used instead of `/`, to breakdown source and output paths
> fix(compile): windows specific paths fix

- src/commands/job/index.ts
- src/commands/request/request.ts
- src/commands/run/run.ts
- src/commands/testing/index.ts
Closes #718 
Added support of insecure connection for `sasjs job` and others if any unsupported
Added `allowInsecureRequests` attribute to `sasjs` instance for 
- `sasjs job`
- `sasjs request`
- `sasjs run`
- `sasjs test`
> fix: allowInsecureRequests supported for rest of the commands

- src/commands/add/addCredential.ts
- src/utils/config.ts
#712 .
When serverUrl is missing in target in config file, instead of giving error prompt user for server url.
When serverUrl is missing in target in config, update the config file.
> When serverUrl is missing in target, prompt the user to provide

- src/commands/deploy/internal/getDeployScripts.ts
- src/commands/deploy/spec/getDeployScripts.spec.ts
- src/utils/test.ts
Fixes https://github.com/sasjs/cli/issues/771
Use the `buildOutputFileName` when determining the set of deploy scripts to run for a SAS9 deploy.
* Take the `buildOutputFileName` from the target buildConfig, and if unavailable fallback to `{target.name}.sas`.
Mocked:
Server:
> fix(sas9-support): consider build output filename when deployServicePack is true

- src/commands/web/adjustIframeScript.ts
When running streaming apps on Viya, the iframe is not in focus
This fix puts the focus on the iframe
Added `window.focus()`
```bash
git clone https://github.com/sasjs/rockroller
cd rockroller
sasjs add cred -t viya
sasjs cbd
```
click the link, and it should be possible to immediately play the game without having to click the screen first
> fix: adding focus to child iframe when running streaming app

- jest.config.js
- jest.server.config.js
- src/cli.spec.ts
- src/commands/add/spec/add-credential.spec.ts
- src/commands/add/spec/add-target.spec.ts
- src/commands/compile/spec/compile.spec.ts
- src/commands/compile/spec/copyFilesToBuildFolder.spec.ts
- src/commands/context/index.ts
- src/commands/context/spec/context.spec.server.ts
- src/commands/folder/spec/delete.spec.server.ts
- src/commands/job/spec/job.spec.server.ts
- src/commands/testing/index.ts
- src/commands/testing/spec/testing.spec.server.ts
1. Mock context `creating`, `editing` and `deleting` during `context` test.
2. Fix clearing all mocks while running tests.
3. Add test URL while executing `sasjs test` command.
Mocked:
Server:
> Output test url during running sasjs test command

- package-lock.json
- package.json
- src/commands/build/build.ts
- src/commands/compile/compile.ts
- src/commands/deploy/deploy.ts
- src/commands/web/index.ts
- src/commands/web/sasjsout.ts
No Github issues to link
Summary of issues:
- `sasjs deploy` is throwing errors (parsing log error for `SAS9`)
- `sasjs web` should really be in `sasjs compile` not `sasjs build`
- CSS is being base64 encoded twice
- add mime type to use for OGG
Moved code for processing for `webStream` from `build.ts` to `compile.ts`
Updated `deploy.ts` for `executeScriptSAS9` result log.
Updated `web/index.ts`
- to avoid encoding of content twice 
Updated `sasjsout.ts`
- to support OGG file as well 
Mocked:
Server:
> fix(web): removed double encoding of CSS issue

- package-lock.json
- package.json
- src/commands/build/internal/config.ts
- src/commands/compile/compileSingleFile.ts
- src/commands/compile/internal/compileTestFile.ts
- src/commands/compile/internal/config.ts
- src/commands/compile/internal/getAllJobFolders.ts
- src/commands/compile/internal/getAllServiceFolders.ts
- src/commands/compile/spec/compile.spec.ts
- src/commands/deploy/deploy.ts
- src/commands/docs/generateDocs.ts
- src/commands/docs/internal/getFoldersForDocs.ts
- src/commands/request/request.ts
- src/commands/run/run.ts
- src/commands/servicepack/deploy.ts
- src/commands/web/index.ts
- src/constants.ts
- src/utils/config.ts
- src/utils/spec/utils.spec.ts
- src/utils/utils.ts
Closes #794 
resolve paths with `~` in sasjsConfig.
Added `getAbsolutePath` to `utils/utils.ts`, and extracted logic from `commands/*`
Mocked:
Server:
> fix: resolve tilde in sasjs config paths

- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/spec/loadDependencies.spec.ts
- src/commands/deploy/spec/cbd.spec.server.ts
Closes #861 
Should add macro variables while `sasjs compile` for `jobs`.
Added similar functionality to `jobs` for having job variables 
For example: 
>* Job Variables start;
>
>%let macrovar=macro value;
>%let macrovar2=macro value2;
>
>* Job Variables end;
Updated `getVars` function as well.
> feat(compile): Add macro variables for jobs

- .github/workflows/run-tests-windows.yml
- .github/workflows/run-tests.yml
- src/commands/build/build.ts
- src/commands/create/spec/create.spec.ts
- src/commands/deploy/deploy.ts
- src/commands/deploy/internal/deployToSasViyaWithServicePack.ts
- src/commands/deploy/spec/cbd.spec.server.ts
- src/commands/servicepack/deploy.ts
- src/commands/servicepack/servicePackCommand.ts
- src/commands/servicepack/spec/servicepack.spec.server.ts
- src/commands/servicepack/spec/servicepackCommand.spec.ts
- src/commands/shared/deployToSasViyaWithServicePack.ts
- src/types/index.ts
- src/types/servicePack.ts
Adapter issue: https://github.com/sasjs/adapter/issues/492
Remove paths from servicePack.json and have base64 encoded string. It should be portable and self-contained.
Types added for:
- `ServicePack`
- `ServicePackMember`
Updated :
- `build.ts` for saving base64 encoded string to servicepack and 
- `deploy.ts` for decoding base64 and send to adapter as code string.
++
- `sasjs deploy` and `sasjs servicepack` were having duplicate code for `deployToSasViyaWithServicePack`, is DRY now.
- `deployToSasViyaWithServicePack` is placed in shared folder.
Mocked:
Server:
> fix: paths removed from service-pack and having base64 strings

- package.json
preinstall script is causing problem as checkNodeVersion script is not being included in package therefore, remove this script for now.
> fix: remove preinstall and prebuild scripts

- .github/workflows/run-tests-windows.yml
- src/utils/test.ts
Closes #945 
Fix specs using latest(1.9.2) version of doxygen.
It turns out that just specs were failing. Doxygen 1.9.2 works fine and supported with CLI.
Updated specs for `index.html` file 
Updated version restriction from github workflow
> test(docs): updated spec checks for docs

- src/commands/compile/internal/compileServiceFile.ts
- src/commands/compile/internal/spec/compileTestFile.spec.ts
- src/commands/compile/internal/spec/testFiles/macros/testMacro.test.sas
Closes #1047 
Add `macroVars` to test macro files.
Add check if a file is a test when loading dependencies in `compileServiceFile` function.
Mocked:
Server:
> Fix test macro compilation

- src/commands/compile/internal/compileTestFile.ts
- src/commands/compile/spec/compile.spec.ts
closes #879 
Fix issue with `sasjs compile` command running from subfolder.
1. Changed `process.currentDir` to `process.projectDir` in `compileTestFile.ts`.
2. Add unit test covering such a scenario.
Mocked:
Server:
> fix(sasjs-test): fix bug with compilation from sub folder

- src/commands/job/jobCommand.ts
- src/commands/job/spec/jobCommand.spec.ts
Closes #878 
- Add `exec` subcommand alias to `sasjs job execute` command.
- Updated `jobCommand.ts`.
- Updated `jobCommand.spec.ts`.
Mocked:
Server:
> feat(job-command): add exec subcommand alias

- package-lock.json
- package.json
- src/commands/compile/internal/compileServiceFile.ts
- src/commands/deploy/spec/cbd.spec.ts
Addresses feature needed in https://github.com/sasjs/adapter/issues/607
[Link any related issue(s) in this section.](https://github.com/sasjs/adapter/issues/607)
Enable special missings to be returned to JS
Added the `missing=` option in the webout() macros
> feat: adding support for special missings

- package-lock.json
- package.json
No issue to link.
`sasjs/adapter` version bump `3.3.0` to `3.3.1`
There are no code changes.
> fix: sasjs/adapter version bump

- .github/reviewer-lottery.yml
- package-lock.json
- package.json
- src/commands/compile/compile.ts
- src/commands/compile/internal/compileJobFile.ts
- src/commands/compile/internal/loadDependencies.ts
- src/commands/compile/internal/spec/compileTestFile.spec.ts
- src/commands/compile/spec/loadDependencies.spec.ts
- src/commands/deploy/spec/cbd.spec.ts
- src/config.json
- src/utils/config.ts
- src/utils/test.ts
Closes #1086 
- Add `Binary Files` support to `sasjs compile` command.
- Bump `@sasjs/utils` and `@sasjs/adapter`.
- Adjust user list for review lottery.
- Adjusted logic around `sasjs compile` command.
- Changed `reviewer-lottery.yml`.
Mocked:
Server:
> Binary files support

- .github/dependabot.yml
We get a lot of dependabot alerts due to our core components requiring frequent upgrades.  The volume of these in our PR queue distracts from the more meaningful ones (ie, those adding features).  We can safely reduce these (security ones will still come through).  When upgrading one package, upgrade them all, would be a general rule to address the 'un-raised' dependabots in advance.
None
Tidy up the PR queue
Updated dependabot frequency
> chore: reducing dependabot limit to 3 and restricting to production

- src/commands/request/spec/request.spec.server.ts
- src/commands/testing/internal/saveOutput.ts
- src/utils/getLogFilePath.ts
- src/utils/utils.ts
- Fix `executeShellScript` utility for Windows.
- Fix `saveLog` function for Windows.
- Add `sh` prefix `executeShellScript` utility for Windows.
- Replace `path.sep` with `/`.
Mocked:
Server:
> fix: fixed executeShellScript utility and saveLog function

- README.md
previous commit did not trigger a release - hence making this (very minor) change.  Reason for this change - the badge is very slow to update, which doesn't look good in the README.
> fix(readme): updating readme.

- package-lock.json
- package.json
- src/commands/testing/spec/testing.spec.server.ts
- src/commands/testing/test.ts
Closes #1108 
- Add `@sasjs/server` support to `sasjs test` command
- Added logic to support `SASJS` `ServerType`.
- Added unit test to cover the new functionality.
Mocked:
Server (without `request.spec.server`):
> feat(test-command): add @sasjs/server support

- .gitpod.yml
- package-lock.json
- package.json
- src/commands/deploy/deploy.ts
- src/commands/testing/spec/testing.spec.server.ts
- src/commands/testing/test.ts
No issue to link
`sasjs test` should work with / without Auth config
Used same `.request()` function of adapter, which we are using for `SAS9` and `SASVIYA`
removed unused variables such as `isLocal`
refactored code from `if else` to `switch`
This also includes changes from another PR:
* bump adapter & core
* move checkNodeVersion to `prepare` script
* remove standard-version (due to vulnerabilities)
Mocked:
Server (without request.spec.server):
> fix: using same request function of adapter for all servers + removed duplicate code

- package-lock.json
- package.json
- src/commands/testing/test.ts
https://github.com/sasjs/server/issues/68
Enabling parsing of new log format on sasjs/server in the adapter
Log is captured line by line rather than as a single string
Mocked:
Server (without `request.spec.server` and `testing.spec.server`):
> fix: bumping adapter with log parsing fix for sasjs/server

- src/commands/job/spec/jobCommand.spec.ts
Forgot to remove `it.only` from previous PR.
Mocked:
Server:
> chore: remove it.only from test cases to avoid test skipping

- .github/FUNDING.yml
This is a bump as the previous one did not get picked up in the auto-release!
The actual new feature here is the deprecation of lua in the streaming apps capability, so that it will work on Viya 4.  See:  https://github.com/sasjs/cli/pull/1139
> fix: funding.yml

- src/commands/compile/compile.ts
closes #1094 
`sasjs compile` should not throw if sasjs web process fails.
Removed throw err and also details of err (stack)
> fix(compile): not throwing for sasjs web while compile

- src/commands/request/request.ts
none
* fix logic that caused the failure of request.spec.server
* if result attribute is present in the response, use that as a response
* if the resultant response is string, try to parse it into json
* if result is not present in response and log is there, remove log from response and use whole response for writing output file.
> fix: logic causing failiur of request.spec.server

- src/commands/create/create.ts
- src/commands/create/spec/angularAppFiles.ts
- src/commands/create/spec/create.spec.ts
- src/commands/create/spec/reactAppFiles.ts
- src/utils/test.ts
- src/utils/utils.ts
Closes #1159 
- On `sasjs create` command using SASjs seed apps a docs submodels also need to be cloned.
- Add `--recurse-submodules` attribute to `git clone` command within `createApp` utility.
> feat(create): enable git clone with submodels

- package-lock.json
- package.json
- src/commands/add/addTarget.ts
closes #1151 
- Avoid extra empty attributes in creating of the target.
- `saveWithDefaultValues` param is set to false for `saveConfig` function.
> fix: sasjs add should not add empty config

- src/commands/compile/compile.ts
- src/commands/compile/spec/compile.spec.ts
Fix compilation duplicates discovered in `DataController`.
- Removed not existing services in `compileServiceFolder` function.
- Removed not existing jobs in `compileJobFolder` function.
- Added a unit covering this scenario.
> fix(compile): fixed duplicates while compilation

- package-lock.json
- package.json
The latest CLI update is no longer picking up the project core - so as a short term measure, bumping the CLI core to latest
> fix: bumping sasjs/core

- src/utils/setConstants.ts
- src/utils/spec/setConstants.spec.ts
- src/utils/utils.ts
#1113 
- Use `@sasjs/core` located in project's dependencies as first choice for project compilation.
- Adjusted `getNodeModulePath` utility.
- Adjusted `setConstants.spec`.
> fix(compile): fixed getNodeModulePath

- src/utils/utils.ts
When running `sasjs create` command after removing `.git` folder and installing dependencies `prepare` command was not running since it wasn't a git repository.
I added `git init`.
> fix: create command git init fix

- src/commands/web/internal/sasjsout.ts
Where attributes are HTML tags rather than a JS object.
No issue - but the problem has arisen in contexts where strict CSP is applied.
Avoid dependency on JS objects in index.html
SAS code updated in a backwards compatible fashion
Mocked:
Server(without `request.spec.server` and `run.spec.server`):
> fix: enabling dynamic streaming apps 

- package-lock.json
- package.json
The previous change caused problems with webout on wlatin1 encoded SAS 9 Stored Process windows environments
Fix the aforementioned issue
Bumped core to enable this fix: https://github.com/sasjs/core/pull/266
> fix: bumping core to fix the latin1 sas9 issue

- src/commands/build/build.ts
#1218
Enable the choice of serverName when deploying to SAS 9 with SAS code
* Added server=&serverName to build.ts mm_createwebservice invocation
* Added `%let servername=$(servername);` to the build.sas where servertype is SAS9
> feat: enabling choice of serverName in SAS 9 code deploys

- package-lock.json
- src/commands/compile/internal/spec/compileTestFile.spec.ts
- src/commands/deploy/spec/cbd.spec.ts
- src/commands/testing/spec/testing.spec.ts
- src/commands/web/internal/createAssetServices.ts
- src/commands/web/internal/getAssetPath.ts
- src/commands/web/internal/getWebServiceContent.ts
- src/commands/web/internal/modifyLinksInContent.ts
- src/commands/web/internal/sas9/createClickMeService.ts
- src/commands/web/internal/sas9/generateAssetService.ts
- src/commands/web/internal/sas9/getWebServiceContent.ts
- src/commands/web/internal/sas9/index.ts
- src/commands/web/internal/sasViya/createClickMeFile.ts
- src/commands/web/internal/sasViya/index.ts
- src/commands/web/internal/sasjsout.ts
- src/commands/web/internal/updateAllTags.ts
- src/commands/web/internal/updateLinkTag.ts
- src/commands/web/internal/updateScriptTag.ts
- src/commands/web/internal/updateStyleTag.ts
- src/commands/web/web.ts
- src/constants.ts
- src/utils/setConstants.ts
#1219 
Instead of three forward slashes we need to use static GUID
Changed `sasjsout.ts` string to function.
Using `sas9GUID` variable from `process.sasjsConstants` as GUID for paths.
- De-coupled code for web.ts
- moved sas9 explicit modules to sas9 folder
- moved sasviya explicit modules to sasViya folder
- add JSDoc comments on them
- used switch for serverType decisions (making it serverType explicit code, not using if-else anymore)
> fix(web): compiling for SAS9 streaming, replaced three slashes with GUID

- package-lock.json
- package.json
- src/commands/compile/internal/spec/compileTestFile.spec.ts
https://github.com/sasjs/lint/issues/166
Bumping core (for more efficient JSON generation) and lint (for ignoring particular sas files)
Bumped @sasjs/core and @sasjs/lint
> fix: bumping sasjs/core and sasjs/lint

- package-lock.json
- src/commands/add/internal/input.ts
Fixes #1235
- Default `client` to `clientID1` when running `sasjs auth` on `SASJS` server type.
- [] All unit tests are passing (`npm test`).
> fix: sasjs server type default to clientID1

- .github/workflows/run-tests-windows.yml
Not able to download and run latest [sasjs/server release](https://github.com/sasjs/server/releases)
Fix windows related command for CI/CD
7z commandline on windows not supporting sasjs/server archive
- using npm package to unzip
Running sasjs/server in background
Before running mocked tests, displaying sasjs/server execution log
> fix(pipeline):  running sasjs server on windows

- package-lock.json
- package.json
- src/commands/job/internal/execute/sas9.ts
- src/commands/job/internal/execute/sasjs.ts
- src/commands/job/internal/utils.ts
- src/commands/job/jobCommand.ts
* bump adapter version
* handle response from `executeJobSASjs`
* implement logic for handling `-o` flag for `sasjs job execute` when server type is `sasjs` 
* Create a utility function for saving output
> fix: handle updated response from sasjs.executeJobSASjs method

- package-lock.json
- package.json
* calling checkNodeVersion script in preinstalling and prebuild steps causes some unexpected problems. So, removed the invocation of this script from the package.json file and rather add a new script that will advise using node lts version
* update versions of adapter, utils and core
> fix: remove the invocation of checkNodeVersion script

- src/commands/docs/internal/getDotFileContent.ts
closes #1260
* get all files for generating lineage even from deeply nested subfolders
* use `listFilesAndSubFoldersInFolder` utility function instead of `listFilesInFolder`
> fix: include files from subfolders for generating lineage

- package-lock.json
- package.json
- src/commands/compile/internal/compileFile.ts
- src/commands/compile/internal/compileTestFile.ts
- src/commands/compile/internal/spec/compileTestFile.spec.ts
- src/commands/compile/spec/compileCommand.spec.ts
- src/commands/compile/spec/loadDependencies.spec.ts
- src/commands/deploy/spec/cbd.spec.ts
- src/utils/utils.ts
Closes #1191 
- Stop adding pre-code to services and tests in `@sasjs/cli` because it is added by `@sasjs/utils`. 
- Removed `getPreCodeForServicePack` function from the code base.
- Fixed unit tests covering `loadDependencies` function.
> Issue 1191

- package-lock.json
- package.json
https://github.com/sasjs/lint/issues/132
Enabling latest lint features in CLI
`npm i @sasjs/lint@latest`
> fix: bumping sasjs/lint

- package-lock.json
- package.json
- src/commands/fs/fsCommand.ts
- src/commands/fs/spec/fsCommand.spec.ts
- src/types/command/commandBase.ts
- src/utils/config.ts
closes #1282
* If sasjs fs sync is executed without arguments then we should check the default (or -t specified) target in the project (and then the user-level) config file for the syncDirectories array.
* made localFolder and remoteFolder optional and replaced with just local (alias `l`) and remote (alias `r`)
* added a config utility to get all sync directories from target and root of sasjs config
* loop on syncDirectories array returned from `getSyncDirectories`
> fix: sasjs fs sync with no arguments should deploy per the sasjsconfig

- package-lock.json
- package.json
https://github.com/sasjs/core/issues/320
Bumping core so that latest webout macros are deployed with `sasjs compile`
`npm i @sasjs/core@latest`
> fix: bumping core to 4.45.1

- package-lock.json
- package.json
- src/commands/fs/fsCommand.ts
closes #1289
* bump `chalk` dependency from `4.1.2` -> `5.1.2`
* bump `yargs` dependency from `17.2.1` -> `17.6.2`
> fix: bump dependencies

- src/utils/config.ts
* previously we were not passing the context name while creating sasjs adapter's instance. So, it was using the default context all the time.
* pass target.contextName to the constructor of adapter
> fix: use correct context name while creating sasjs adapter instance

- package-lock.json
- package.json
n/a
Enabling the latest version of lint in the CLI (`noTabs` feature)
Bumped lint (also core)
> fix: bumping lint to v2 (also core to 4.45.3)

- package-lock.json
- package.json
n/a
bump core to 4.45.4
`npm i @sasjs/core@latest` then fixing the version by removing the `^` in package.json
> fix: bump core to 4.45.4

- package-lock.json
- package.json
- src/commands/fs/fsCommand.ts
> fix: update @sasjs/utils version

- package-lock.json
- package.json
- src/commands/lint/lintCommand.ts
- src/commands/lint/processLint.ts
- src/commands/lint/spec/lintCommand.spec.ts
- src/types/command/commandBase.ts
closes #1304 
* In the lint command if any arguments ate provided after the subCommand, they will be treated as filter patterns. And `lint` or `lint fix` will be performed on files that match the specified pattern.
> feat: add the ability to lint or lint fix some specific files/folders

- src/commands/init/init.ts
- src/commands/init/spec/init.spec.ts
- src/config.json
- src/utils/spec/utils.spec.ts
- src/utils/utils.ts
closes #1305
* on sasjs init command, create minimal `sasjs/sasjsconfig.json` file
* sasjs init command should not destroy existing packages.json
* fix logic for updating the `.gitignore` file
* pass just folder name instead of whole path to `isExistingProject` function
> fix: improvements to sasjs init

- package-lock.json
- package.json
Adding the following rules in `sasjs lint`:
* [allowedGremlins](https://github.com/sasjs/lint#allowedgremlins)
* [maxDataLineLength](https://github.com/sasjs/lint#maxdatalinelength)
* [maxHeaderLineLength](https://github.com/sasjs/lint#maxheaderlinelength)
> feat: new linting rules

- src/commands/testing/internal/saveOutput.ts
- src/commands/testing/spec/testing.spec.ts
- src/commands/testing/test.ts
- src/types/testing.ts
closes #1284
add the following additional info to JSON file:
* csv_result_path
* xml_result_path
* coverage_report_path
* failed_to_complete
* completed_with_failures
* tests_with_results
* tests_that_pass
* target_name
* target_server_url
* target_server_type
* local_date_time
* local_user_id
* local_machine_name
> fix: add additional info to json file after completion of sasjs test

- src/commands/deploy/internal/deployToSASJSWithServicePack.ts
- src/commands/deploy/internal/executeDeployScriptSasViya.ts
> fix: sasjs deploy should return error when deployment fails

- package-lock.json
- package.json
> fix: bump sasjs lint version to 2.2.2

- src/commands/build/build.ts
- src/commands/compile/compileSingleFile.ts
When `@sasjs/cli` functions are used in `@sasjs/vscode-extension` the `process` object is undefined and the current folder has to be provided in order to use the `compile` function
- Improve the `compile` function.
- Added the `currentFolder` optional attribute to the `compile` function.
> feat(compile): added currentFolder argument

- package-lock.json
- package.json
- src/commands/compile/spec/compile.spec.ts
- src/commands/fs/fsCommand.ts
- src/types/command/targetCommand.ts
- src/utils/setConstants.ts
closes #1320
BREAKING CHANGE
* add two new attributes (sasjsBuildFolder and sasjsResultsFolder) in configuration and targetJson interfaces
* remove buildOutputFolder and buildResultsFolder from build config
* There should be check at both the root and target level for sasjsBuild and sasjsResults folders (if the setting is in both, the target overrules)
* added a new function `updateSasjsConstants`, which updates the `process.sasjsConstants` based on the target.
* This function is called once from `getTargetInfo` method of TargetCommand's class
> BREAKING CHANGE: bump sasjs utils

- src/commands/compile/compile.ts
- src/commands/compile/compileCommand.ts
- src/commands/compile/spec/compile.spec.ts
closes #1206
- Terminate the compilation process if `testSetUp` option is present and test file compilation failed.
- Terminate the compilation process if `testTearDown` option is present and the test file compilation failed.
- Modified `src/commands/compile/compile.ts` to throw an error if there was an error during the compilation of the test file.
- Added unit tests to cover cases when `testSetUp` or `testTearDown` option is present and test file compilation failed.
> fix(compile): terminate compilation if testSetUp or testTearDown failed

- package-lock.json
- package.json
- src/commands/help/help.ts
Closes #1340 
- Add `compile` option to `run` command documentation provided by `help` command.
- Bump `@sasjs/utils` to the latest version.
- Updated `src/commands/help/help.ts`.
- Adjusted `@sasjs/utils` version in `package.json`.
> fix(help): added compile option to run command

- .github/workflows/run-tests.yml
- src/commands/compile/spec/compile.spec.ts
Closes #1341 
- Add coverage report to CI on pull requests.
- Added `Generate coverage report` step to `.github/workflows/run-tests.yml`.
- Removed `Run mocked tests` step from `Node.js CI` because these tests will be conducted as during `Generate coverage report` step.
> chore(ci): added generate coverage report step

- package-lock.json
- package.json
Closes https://github.com/sasjs/lint/issues/209
It is now possible to put a .sasjslint file in the user home directory to provide global lint settings. 
Bumped @sasjs/lint to latest version
> feat(lint): support for global settings

- package-lock.json
- package.json
Related to https://github.com/sasjs/adapter/pull/817
- Use `@sasjs/adapter` with fixed `request` method for `SASJS` server type.
- Bumped `@sasjs/adapter` to `4.5.1` version.
> fix(adapter): bumped @sasjs/adapter with fixed request method

- package.json
- src/commands/run/run.ts
- src/commands/run/spec/run.spec.ts
- src/utils/utils.ts
- `executeScript` method of `@sasjs/adapter` returns an object for `SASJS` server type.
- Leave only server-side tests with `SASJS` server type.
- Adjust the way the execution result of `executeScript` method is handled.
- Adjusted `executeOnSasJS` function in `src/commands/run/run.ts`.
- Added mocked `src/commands/run/spec/run.spec.ts` unit test for `SASJS` server type.
- Adjusted `testServerTypes` property in `package.json`
> Fixed run command for SASJS server type

- package-lock.json
- package.json
- src/commands/add/addCredential.ts
- src/commands/compile/internal/compileTestFile.ts
- src/commands/compile/internal/spec/compileTestFile.spec.ts
- src/commands/help/help.ts
- src/commands/job/internal/execute/sas9.ts
- src/commands/job/internal/execute/sasjs.ts
- src/commands/job/internal/execute/viya.ts
- src/commands/job/internal/utils.ts
- src/commands/job/jobCommand.ts
- src/commands/job/spec/execute.spec.ts
- src/commands/job/spec/job.spec.server.viya.ts
- src/commands/job/spec/jobCommand.spec.ts
- src/commands/run/run.ts
- src/commands/run/spec/run.spec.ts
- src/utils/config.ts
- src/utils/saveLog.ts
- src/utils/spec/config.spec.ts
Closes #1356
- Deprecate `--returnStatusOnly` flag in `sasjs job execute` command.
- Implement `--verbose` flag in `sasjs job execute` command.
- Implement `verbose` mode that should be enabled iF `VERBOSE` entry is present in `.env` file.
- Changed `sasjs job` command.
- Adjusted unit tests.
- Changed `getSASjs` utility that should instantiate of `SASjs` class with `verbose` mode on/off.
> feat(verbose): added verbose mode and deprecated --returnStatusOnly

- src/utils/config.ts
- src/utils/spec/config.spec.ts
- Verbose mode should be enabled only by providing `on`(case insensitive) string to `VERBOSE` environment variable.
- Updated logic in `getSASjs` utility.
- Updated unit tests.
> fix(config): fixed verbose mode in getSASjs utility

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/assign-reviewer.yml
- jest.config.js
- src/utils/config.ts
- src/utils/spec/config.spec.ts
- Verbose mode should be enabled if `LOG_LEVEL` environment variable is set to `Trace`(case insensitive).
- Updated logic in `getSASjs` utility.
- Adjusted unit tests covering `getSASjs` utility.
> feat(verbose): enable verbose mode if LOG_LEVEL is trace

- jest.config.js
- package-lock.json
- package.json
- src/commands/flow/execute.ts
- src/commands/flow/internal/spec/executeFlow.spec.ts
- src/commands/help/help.ts
- src/commands/job/internal/execute/sasjs.ts
- src/commands/job/internal/execute/viya.ts
- src/commands/job/jobCommand.ts
- src/commands/job/spec/execute.spec.ts
- src/commands/job/spec/job.spec.server.viya.ts
- src/commands/job/spec/jobCommand.spec.ts
- src/utils/config.ts
Closes #1367 
- Implement `bleached` verbose mode (without extra colors) that can be enabled through environment variable `VERBOSE=BLEACHED` or through `sasjs job execute --verbose bleached` command.
- Fix hardcoded job state polling options for `sasjs job execute` and `sasjs flow execute` commands.
- Refactor logic related to `sasjs job execute` command.
- Bumped `@sasjs/adapter`.
- Fixed job state polling options in `src/commands/flow/execute.ts` to use default polling strategies configured in `@sasjs/adapter` after the first poll.
- Updated `help` command.
- Used instance of `@sasjs/adapter` instead of `SASjsApiClient` in `src/commands/job/internal/execute/sasjs.ts`.
- Fixed job state polling options in `src/commands/job/internal/execute/viya.ts` to use default polling strategies …
> Issue 1367

- package-lock.json
- package.json
- src/commands/add/addTarget.ts
`@sasjs/adapter` couldn't properly parse HTTP responses with statuses `4**` in verbose mode.
- Use `@sasjs/adapter` with improved verbose mode.
- Bumped `@sasjs/adapter`.
> fix(verbose-mode): used fixed @sasjs/adapter

- src/commands/snippets/snippets.ts
- src/commands/snippets/spec/snippets.spec.ts
- src/commands/snippets/spec/testMacros2/macro2.sas
`[in]` and `[out]` `@param` entries don't bring value, but just use limited space in VS Code snippet description.
- Remove `[in]` and `[out]` `@param` entries from snippet description.
- Improved param regular expression in `src/commands/snippets/snippets.ts`.
- Adjusted unit test covering VS Code snippet generation.
> feat(snippets): remove [in] and [out] from @params

- src/commands/snippets/snippets.ts
- src/commands/snippets/spec/snippets.spec.ts
- src/commands/snippets/spec/testMacros2/macro2.sas
`[ianything]` `@param` entries don't bring value, but just use limited space in VS Code snippet description.
- Remove `[anything]` `@param` entries from snippet description.
- Improved param regular expression in `src/commands/snippets/snippets.ts`.
- Adjusted unit test covering VS Code snippet generation.
> feat(snippets): improved @param reg exp

- jest.config.js
- package-lock.json
- package.json
- src/commands/job/internal/execute/viya.ts
- src/commands/testing/spec/testing.spec.ts
- Sometimes SAS API returns the job state `running` when the parent session is not in a `running` state.
- `sasjs job execute` wasn't handling all kind of errors.
- Bump `@sasjs/adapter` that periodically checks parent session state while polling job status.
- Improve error handling in `sasjs job execute` command.
- Fix unit tests that were tacking to much time to complete.
- Bumped `@sasjs/adapter`.
- Fixed error handling in `src/commands/job/internal/execute/viya.ts`.
- Mocked `getString` utility to improve unit tests in `src/commands/testing/spec/testing.spec.ts`.
> @sasjs/adapter bump

- jest.config.js
- package-lock.json
- package.json
- src/commands/add/addCredential.ts
- src/commands/add/internal/input.ts
- src/commands/context/contextCommand.ts
- src/commands/flow/flowCommand.ts
- src/commands/folder/folderCommand.ts
- src/commands/job/jobCommand.ts
- src/commands/job/spec/jobCommand.spec.ts
- src/commands/request/request.ts
- src/commands/shared/deployToSasViyaWithServicePack.ts
- src/utils/config.ts
- src/utils/test.ts
- src/utils/utils.ts
- Bleached verbose mode wasn't working when set through the environment variable.
- `@sasjs/adapter` was treating `idle` parent session state as not healthy while polling the job state.
- Bump `@sasjs/adapter`.
- Fix verbose mode while running `sasjs job execute` command.
- Refactor `@sasjs/adapter` instantiation.
- Fixed `getVerbose` function in `src/commands/job/jobCommand.ts`.
- Adjusted unit tests related to `sasjs job execute` command.
- Fixed `createEnvFileForViya` utility.
- Used `getSASjs` utility to get an instance of `@sasjs/adapter` instead of instantiating it manually .
> Job command improvements

- src/commands/build/build.ts
Closes #1388
Server Name in SAS 9 should be configurable
Updated SAS9-only logic in build.ts
> feat: configurable serverName in SAS 9

- .github/SECURITY.md
- README.md
- package-lock.json
- package.json
bumping @sasjs/lint to enable new option per https://github.com/sasjs/lint/
Also updating README to remove outdated badges, and ran npm audit to bump the dependencies and address vulnerabilities
> feat: new option for sasjs/lint

- src/commands/build/internal/getLaunchPageCode.ts
- src/commands/deploy/deploy.ts
- src/commands/deploy/internal/executeDeployScriptSasViya.ts
- src/commands/deploy/spec/cbd.spec.server.viya.ts
- src/commands/run/spec/run.spec.server.viya.ts
Related to #1400 
When you run the `CBD` command to deploy a Viya Stream app, the link printed in the terminal no longer includes the `_debug=2` query parameter.
- Removed `_debug=2` from the link printed in the terminal
- Adjusted the `cbd.spec.server.viya`
- Adjusted the `run.spec.server.viya`
- [] All CI checks are green.
> fix(viya): remove `_debug=2` query parameter from deployed URLs

- package-lock.json
- package.json
`sasjs test` has not been working due to a change in Viya, described here: https://communities.sas.com/t5/SAS-Viya/Returning-webout-from-JES-API/m-p/968153
Bumping adapter and sasjs/core to make use of the _omitsessionresults fix
> fix: bump adapter and core to fix JES _webout issue
